apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: 2019-02-28T12:57:41Z
  name: cephfs
  resourceVersion: "13357242"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/cephfs
  uid: 6edd741c-3b58-11e9-b069-1866dabbab47
parameters:
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: cephfs
  claimRoot: /dlkit-volumes
  monitors: 114.212.189.147:6789,114.212.189.125:6789,114.212.189.126:6789
provisioner: ceph.com/cephfs
reclaimPolicy: Delete
volumeBindingMode: Immediate
