apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpldapadmin
  name: phpldapadmin-service
  namespace: openldap
spec:
  type: NodePort
  ports:
    - name: phpldapadmin
      nodePort: 31111
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: phpldapadmin
