apiVersion: v1
data:
  controller_config_file.yaml: |-
    {

    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: pytorch-operator
  name: pytorch-operator-config
  namespace: kubeflow
