apiVersion: v1
data:
  controller_config_file.yaml: |-
    {
        "grpcServerFilePath": "/opt/mlkube/grpc_tensorflow_server/grpc_tensorflow_server.py"
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: tf-job-operator
  name: tf-job-operator-config
  namespace: kubeflow
