apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: pytorch-operator
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: pytorch-operator
  name: pytorch-operator
  namespace: kubeflow
secrets:
- name: pytorch-operator-token-cfn4g
