apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/2zMMQ6DMAyF4b3HeDO06pqtZ6jU3QQjpRDbSgwdUO5eZWd70v/0nSBLHy41qSDgeGLAmmRGwJvLkSK/YtRdHAMyO83khHBio4m32heZIcCX8avTqMaFXEtXqoqw35M+omZTYfGLYxsglPmS6KEaxV7XfeJl0x9au/0BAAD//wEAAP//wlW3BLUAAAA="}'
  creationTimestamp: 2018-12-26T09:14:17Z
  labels:
    app: tf-job-operator
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: tf-job-operator
  name: tf-job-operator
  namespace: kubeflow
  resourceVersion: "32731"
  selfLink: /api/v1/namespaces/kubeflow/serviceaccounts/tf-job-operator
  uid: 9f3db30c-08ee-11e9-9c12-1866dabbab47
secrets:
- name: tf-job-operator-token-mhzgs
