apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: tf-job-operator
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: tf-job-operator
  name: tf-job-operator
  namespace: kubeflow
secrets:
- name: tf-job-operator-token-mhzgs
