apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    ksonnet.io/managed: '{"pristine":"H4sIAAAAAAAA/5yST4sbMQzF7/0YOs8fcjX0ELrbW7ahhUJZQlAcTeqNbRlbM+2y+LsXNX+hSQ97k8fSez8/zRtgct8pF8cRDNBvoah16afZhgRn0MDexS0YeKDk+TVQFGggkOAWBcG8gccN+aLVvnCMJJ3j3nJIHLXZgAztC29aTpRROENtIGKgf2/ai6k2lIRWu/bjhgbPv3SwJLJqlSl5Z7GAmTUgFJJHIb24TXbbD+qVouUo6CLlAuZZjyGgPvwZek7SnyB6Gc7z3YW3bdEX9rwTLrKlnPXb9HEGqwYoTn8ljxCLH+vll4f103zx+G05//QIDUzoR/qcOSjI4Mhvv9JwrpcoP8GcX9Zdsqm1Nrd03yWpaqsGXMCdymXauSL5tYsvo7Ols/E6g/UpA6PBF4F7O1UU9mOgBY9RDtkGLY8IPYntLcfB7S4ah3N7GIS6Uq5CeXKW5tbq9NP/zU47VJkFpvu/QHu0rve9a60f/gAAAP//AQAA//8lVn/hKAMAAA=="}'
  creationTimestamp: 2018-12-26T09:14:18Z
  generation: 1
  labels:
    app.kubernetes.io/deploy-manager: ksonnet
    ksonnet.io/component: tf-job-operator
  name: tf-job-operator-v1beta1
  namespace: kubeflow
  resourceVersion: "17362271"
  selfLink: /apis/extensions/v1beta1/namespaces/kubeflow/deployments/tf-job-operator-v1beta1
  uid: 9f8457aa-08ee-11e9-9c12-1866dabbab47
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      name: tf-job-operator
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        name: tf-job-operator
    spec:
      containers:
      - command:
        - /opt/kubeflow/tf-operator.v1beta1
        - --alsologtostderr
        - -v=1
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        image: registry.cn-hangzhou.aliyuncs.com/njuicscn/tf_operator:v1alpha
        imagePullPolicy: Always
        name: tf-job-operator
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /etc/config
          name: config-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: tf-job-operator
      serviceAccountName: tf-job-operator
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: tf-job-operator-config
        name: config-volume
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-12-26T09:14:18Z
    lastUpdateTime: 2018-12-26T09:14:18Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
